# Generated by Django 3.2.5 on 2021-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
