# Generated by Django 3.2.5 on 2021-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211207_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='No overview', max_length=500),
        ),
    ]
