# Generated by Django 3.2.5 on 2021-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211207_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='No overview', max_length=5000),
        ),
    ]
