# Generated by Django 3.2.5 on 2021-12-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='nickname',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
