# Generated by Django 3.2.5 on 2021-12-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.BigIntegerField(),
        ),
    ]
